### ISSUE TITLE
fatal: Invalid raw date

### ISSUE THREAD

**Issue by PedroVelez** [davisp/ghp-import#82] opened 2020-06-30 22:47 UTC
Hi, thanks for the repository. 

I installed via pip: `pip install ghp_import` without problems

However, when running `ghp-import -n -p -f _build/html/`within my git repository I got:

```
fatal: Invalid raw date "<<XXX>> 1593556860 +0100" in ident:  <XXX> <<XXX>> 1593556860 +0100
fast-import: dumping crash report to .git/fast_import_crash_49369
Traceback (most recent call last):
  File "/Users/XXX/miniconda3/envs/AOS/bin/ghp-import", line 8, in <module>
    sys.exit(main())
  File "/Users/XXX/miniconda3/envs/AOS/lib/python3.8/site-packages/ghp_import.py", line 238, in main
    run_import(git, args[0], opts)
  File "/Users/XXX/miniconda3/envs/AOS/lib/python3.8/site-packages/ghp_import.py", line 185, in run_import
    pipe.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
```

I am using Python 3.8.3 and conda 4.8.3

any help?

thanks!.

**Comment by PedroVelez** [comment] 2020-07-01 12:52
[Update] after reading several issues, somehow similar, I modified my user name (Pedro Velez) to avoid any space  but I still get the same `fatal: Invalid raw date ` It seems related to the way the date from the commit is used, but I am not able to fix it.

**Comment by c-w** [comment] 2020-07-25 00:53
This looks similar to https://github.com/davisp/ghp-import/issues/60. Could you report what the following command returns for you?

```py
import time
print(time.strftime('%z'))
```

**Comment by c-w** [comment] 2020-07-25 00:58
Resolving in favor of #60 as this seems to be the same root cause. Please add any additional questions or follow-up to that other issue. Thanks!

**Closed by c-w** 2020-07-25 00:58 UTC

**Comment by c-w** [comment] 2020-08-08 23:46
This has been released in [0.6.0](https://pypi.org/project/ghp-import/0.6.0/).

**Comment by imdeepmind** [comment] 2021-12-08 15:05
I'm using version `2.0.2` of ghp-import and Python 3.8.10. Still getting this error. Any idea what's wrong?

I'm getting the following output from the code you mentioned above.
```python
>>> import time
>>> print(time.strftime('%z'))
+0530
>>> 
```

**Comment by c-w** [comment] 2021-12-08 16:53
Could you provide me with the full stack trace @imdeepmind? Also, what OS and git version are you on?

**Comment by imdeepmind** [comment] 2021-12-08 17:34
Stacktrace:
```
fatal: Invalid raw date "<email@email.com> 1638984718 +0530" in ident: Abhishek Chatterjee <imdeepmind> <email@email.com> 1638984718 +0530
fast-import: dumping crash report to .git/fast_import_crash_19516
Traceback (most recent call last):
  File "/home/imdeepmind/Desktop/workspace/hocrox/env/bin/ghp-import", line 8, in <module>
    sys.exit(main())
  File "/home/imdeepmind/Desktop/workspace/hocrox/env/lib/python3.8/site-packages/ghp_import.py", line 278, in main
    ghp_import(args[0], **opts.__dict__)
  File "/home/imdeepmind/Desktop/workspace/hocrox/env/lib/python3.8/site-packages/ghp_import.py", line 257, in ghp_import
    run_import(git, srcdir, **opts)
  File "/home/imdeepmind/Desktop/workspace/hocrox/env/lib/python3.8/site-packages/ghp_import.py", line 192, in run_import
    pipe.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
```

OS Version: OS: Linux Mint 20.1 x86_64

Git Version: git version 2.25.1

**Comment by c-w** [comment] 2021-12-08 17:45
Looks like this is an unrelated issue. Could you provide the output of `git config --list` too, thanks!

**Comment by imdeepmind** [comment] 2021-12-08 18:28
Here it is @c-w 
```
(env) imdeepmind@imdeepmind:~/Desktop/workspace/hocrox(enhancement/add-doc-site)$ git config --list
user.email=x.x@email.com
user.name=Abhishek Chatterjee <imdeepmind>
alias.add-commit=!git add -A && git commit
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@github.com:imdeepmind/hocrox.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
```

**Comment by c-w** [comment] 2021-12-08 19:08
Could you try removing the `<imdeepmind>` from the user name: `git config user.name "Abhishek Chatterjee"`? I wonder if that's throwing off the [fast-import date parser](https://www.git-scm.com/docs/git-fast-import#_date_formats).

**Comment by imdeepmind** [comment] 2021-12-09 18:24
Thanks @c-w, changing the name user.name fixed the issue
